#!/bin/bash
#
#

export PATH="/usr/local/bin:/usr/local/sbin:/usr/local/Cellar/ruby/2.0.0-p195/bin:/home/diego/TEE-CLC-12.0.2:$PATH"

# tfs
export TF_AUTO_SAVE_CREDENTIALS="0"

# go
export GOPATH=$HOME/Dev/go
export PATH=$PATH:$GOPATH/bin

# jvm
export MAVEN_OPTS="-Xmx2048M -Xss128M -XX:+CMSClassUnloadingEnabled"